# Generated by Django 6.1.1 on 2026-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=64, unique=True)),
                ("sender_id", models.CharField(max_length=64)),
                ("recipient_id", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("P2P", "Person to Person"),
                            ("CASH_IN", "Cash In"),
                            ("CASH_OUT", "Cash Out"),
                            ("MERCHANT_PAYMENT", "Merchant Payment"),
                            ("BILL_PAYMENT", "Bill Payment"),
                        ],
                        default="P2P",
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
